export const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
export const PROJECT_ID = process.env.NEXT_PUBLIC_IPFS_PROJECT_ID;
export const PROJECT_SECRET = process.env.NEXT_PUBLIC_IPFS_PROJECT_SECRECT;
export const PROFILE_IMAGE_URL = process.env.NEXT_PUBLIC_PROFILE_IMAGE_URL;
export const CALLIGRAPHY_IMAGE_URL = process.env.NEXT_PUBLIC_CALLIGRAPHY_IMAGE_URL;